name: e_demo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
assets: -assets/lottie/
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  lottie: 2.6.0
  flutter: 
    sdk: flutter
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flutter_custom_carousel_slider: ^1.2.0
  cached_network_image: ^3.2.3
  flutter_custom_tab_bar: ^1.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/lottie/

